In [1]:
'''

@Author: Vighnesh Harish Bilgi
@Date: 2022-12-09
@Last Modified by: Vighnesh Harish Bilgi
@Last Modified time: 2022-12-09
@Title : Data Modelling - 2 : Wealth Accounts Datasets

'''

'\n\n@Author: Vighnesh Harish Bilgi\n@Date: 2022-12-09\n@Last Modified by: Vighnesh Harish Bilgi\n@Last Modified time: 2022-12-09\n@Title : Data Modelling - 2\n\n'

In [2]:
import mysql.connector
import pandas as pd
import os

In [3]:
sql_password = os.environ.get("sql_password")

### Custom functions to connect to the mysql server and iterate the cursor

In [4]:
def iterate_cursor(db_cursor):
    """
    Description:
        Take MySQLCursor argument from parameter "db_cursor" and iterate and print the selected records with its column name 
        (i.e. a SELECT or SHOW command must be called before iterate_cursor() is called).
    Parameter:
        MySQLCursor db_cursor
    Return:
        No values returned.
    """
    print(db_cursor.column_names)
    for db in db_cursor:
        print(db)

def connect_to_sql():
    """
    Description:
        To setup connection to MySQL Server, pass hostname , user and password as arguments to parameters "host","user" and "passwd" of connect() respectively.
        connect() is method from module "mysql.connector". Once the connection is set. Return it.
    Parameter:
        No parameters.
    Return:
        MYSQLConnection db_connection
    """

    db_connection = mysql.connector.connect(
    host= "localhost",
    user= "root",
    passwd= sql_password
    )

    return db_connection

### Custom functions to create database 'accounts'

In [5]:
def create_database(db_cursor):
    """
    Description:
        Take MySQLCursor argument from parameter "db_cursor" and create database
        Return updated cursor. 
    Parameter:
        MySQLCursor db_cursor
    Return:
        MySQLCursor db_cursor
    """
    print("Creating DATABASE - accounts\n")
    db_cursor.execute("DROP DATABASE IF EXISTS accounts")
    db_cursor.execute("CREATE DATABASE accounts")

    print("Showing all databases...")
    db_cursor.execute("SHOW DATABASES")
    iterate_cursor(db_cursor)

    print("\nUsing accounts")
    db_cursor.execute("USE accounts")

    return db_cursor

### Custom function to create tables

In [6]:
def create_table(db_cursor,table,schema):
    """
    Description:
        Take MySQLCursor argument from parameter "db_cursor" and create table.
        Return updated cursor. 
    Parameter:
        MySQLCursor db_cursor,
        string table,
        string schema
    Return:
        MySQLCursor db_cursor
    """

    print(f"Creating TABLE - {table}")
    db_cursor.execute(f"""CREATE TABLE IF NOT EXISTS {table} {schema}""")

    print("Showing all tables under accounts...")
    db_cursor.execute("SHOW TABLES")
    iterate_cursor(db_cursor)

    print(f"Showing '{table}' Table schema  ...")
    db_cursor.execute(f"DESCRIBE {table}")
    iterate_cursor(db_cursor)
    return db_cursor

### Custom function to insert records into tables

In [7]:
def insert_table(db_cursor,table,cols,record):
    """
    Description:
        Take MySQLCursor argument from parameter "db_cursor" and perform Create Operation of CRUD by applying execute() on cursor.
        Return updated cursor. 
    Parameter:
        MySQLCursor db_cursor,
        string table,
        string cols,
        string record
    Return:
        MySQLCursor db_cursor
    """

    print(f"Inserting record {record} into table...\n")
    db_cursor.execute(f"""INSERT INTO {table} {cols}
                        VALUES {record}""")
    return db_cursor

### Custom function to show all records from table

In [8]:
def show_all_records(db_cursor,table):
    """
    Description:
        Take MySQLCursor argument from parameter "db_cursor" and show all records from table.
        Return updated cursor. 
    Parameter:
        MySQLCursor db_cursor
    Return:
        MySQLCursor db_cursor
    """

    print("Printing records from table...\n")
    db_cursor.execute(f"SELECT * FROM {table}")
    iterate_cursor(db_cursor)
    return db_cursor

### Read 'wealth-accountsCountry.csv' into pandas dataframe

In [9]:
accounts_country = pd.read_csv("data/wealth-accountsCountry.csv", encoding='cp1252')
accounts_country.head()

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2020 (expected),"Demographic and Health Survey, 2017/18",NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
1,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2020 (expected),"Multiple Indicator Cluster Survey, 2019/20",NaN,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina
2,ARM,Republic of Armenia,Upper middle income,Europe & Central Asia,IBRD,NaN,Armenian dram,2020 (expected),"Demographic and Health Survey, 2015/16",NaN,...,"Integrated household survey (IHS), 2016",Yes,2014,NaN,2018.0,2012.0,AM,AM,Armenia,Armenia
3,AUS,Commonwealth of Australia,High income,East Asia & Pacific,NaN,NaN,Australian dollar,2016,NaN,Fiscal year end: June 30; reporting period for...,...,"Expenditure survey/budget survey (ES/BS), 2010",Yes,2015-2016,2013.0,2018.0,2013.0,AU,AU,Australia,Australia
4,AUT,Republic of Austria,High income,Europe & Central Asia,NaN,Euro area,Euro,2011. Population figures compiled from adminis...,NaN,A simple multiplier is used to convert the nat...,...,"Income survey (IS), 2015",Yes,2010,2014.0,2018.0,2010.0,AT,AT,Austria,Austria

#### summary of the dataframe

In [10]:
accounts_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Code                                               146 non-null    object
 1   Long Name                                          146 non-null    object
 2   Income Group                                       145 non-null    object
 3   Region                                             146 non-null    object
 4   Lending category                                   107 non-null    object
 5   Other groups                                       52 non-null     object
 6   Currency Unit                                      146 non-null    object
 7   Latest population census                           145 non-null    object
 8   Latest household survey                            119 non-null    object
 9   Special Notes                                      45 non-null     object
 10  National accounts base year                        146 non-null    object
 11  National accounts reference year                   59 non-null     float64
 12  System of National Accounts                        146 non-null    object
 13  SNA price valuation                                146 non-null    object
 14  Alternative conversion factor                      41 non-null     object
 15  PPP survey years                                   138 non-null    object
 16  Balance of Payments Manual in use                  145 non-null    object
 17  External debt Reporting status                     95 non-null     object
 18  System of trade                                    135 non-null    object
 19  Government Accounting concept                      126 non-null    object
 20  IMF data dissemination standard                    145 non-null    object
 21  Source of most recent Income and expenditure data  138 non-null    object
 22  Vital registration complete                        73 non-null     object
 23  Latest agricultural census                         105 non-null    object
 24  Latest industrial data                             128 non-null    float64
 25  Latest trade data                                  142 non-null    float64
 26  Latest water withdrawal data                       140 non-null    float64
 27  2-alpha code                                       145 non-null    object
 28  WB-2 code                                          145 non-null    object
 29  Table Name                                         146 non-null    object
 30  Short Name                                         146 non-null    object
dtypes: float64(4), object(27)
memory usage: 35.5+ KB

#### viewing columns of the dataframe

In [11]:
accounts_country.columns

Index(['Code', 'Long Name', 'Income Group', 'Region', 'Lending category',
       'Other groups', 'Currency Unit', 'Latest population census',
       'Latest household survey', 'Special Notes',
       'National accounts base year', 'National accounts reference year',
       'System of National Accounts', 'SNA price valuation',
       'Alternative conversion factor', 'PPP survey years',
       'Balance of Payments Manual in use', 'External debt Reporting status',
       'System of trade', 'Government Accounting concept',
       'IMF data dissemination standard',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data', '2-alpha code', 'WB-2 code',
       'Table Name', 'Short Name'],
      dtype='object')

#### renaming some columns of the dataframe

In [12]:
accounts_country.rename(columns = {'Code':'country_code', 'Short Name':'short_name','Table Name':'table_name','Long Name':'long_name','Currency Unit':'currency_unit'}, inplace = True)

In [13]:
accounts_country.columns

Index(['country_code', 'long_name', 'Income Group', 'Region',
       'Lending category', 'Other groups', 'currency_unit',
       'Latest population census', 'Latest household survey', 'Special Notes',
       'National accounts base year', 'National accounts reference year',
       'System of National Accounts', 'SNA price valuation',
       'Alternative conversion factor', 'PPP survey years',
       'Balance of Payments Manual in use', 'External debt Reporting status',
       'System of trade', 'Government Accounting concept',
       'IMF data dissemination standard',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data', '2-alpha code', 'WB-2 code',
       'table_name', 'short_name'],
      dtype='object')

#### selecting certain columns of the dataframe for the table 'accounts_country'

In [14]:
accounts_country_clean = accounts_country[['country_code','short_name','table_name','long_name','currency_unit']]
accounts_country_clean.head()

,country_code,short_name,table_name,long_name,currency_unit
0,ALB,Albania,Albania,Republic of Albania,Albanian lek
1,ARG,Argentina,Argentina,Argentine Republic,Argentine peso
2,ARM,Armenia,Armenia,Republic of Armenia,Armenian dram
3,AUS,Australia,Australia,Commonwealth of Australia,Australian dollar
4,AUT,Austria,Austria,Republic of Austria,Euro

### Read 'wealth-accountsData.csv' into pandas dataframe

In [15]:
accounts_data = pd.read_csv("data/wealth-accountsData.csv", encoding='cp1252')
accounts_data.head()

,ï»¿Series Name,Series Code,Country Name,Country Code,1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],1999 [YR1999],2000 [YR2000],...,2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,Human capital (constant 2018 US$),NW.HCA.TO,Albania,ALB,44861001530,43430547992,37131131819,38792147742,42196257452,43611277219,...,6.610924e+10,6.805651e+10,6.853525e+10,7.075229e+10,7.160031e+10,7.248767e+10,7.372787e+10,75716975793,78045555079,81214984640
1,Human capital (constant 2018 US$),NW.HCA.TO,Argentina,ARG,1.37855E+12,1.40471E+12,1.55117E+12,1.7414E+12,1.79004E+12,1.84136E+12,...,2.045920e+12,2.419210e+12,2.953450e+12,2.968890e+12,3.180360e+12,3.128110e+12,3.215850e+12,3.15301E+12,3.22663E+12,3.15994E+12
2,Human capital (constant 2018 US$),NW.HCA.TO,Armenia,ARM,31162180567,32446809421,32562110893,35586495233,35852007081,36048138201,...,5.795380e+10,6.083493e+10,6.729478e+10,7.026139e+10,7.214770e+10,7.320107e+10,8.011339e+10,76522388252,81504751657,84936407008
3,Human capital (constant 2018 US$),NW.HCA.TO,Australia,AUS,5.65711E+12,5.91611E+12,6.03646E+12,6.26521E+12,6.43226E+12,6.58307E+12,...,8.824470e+12,9.242020e+12,9.788920e+12,1.031640e+13,1.049550e+13,1.093710e+13,1.132480e+13,1.12677E+13,1.1503E+13,1.17879E+13
4,Human capital (constant 2018 US$),NW.HCA.TO,Austria,AUT,2.22685E+12,2.20598E+12,2.18531E+12,2.23164E+12,2.27984E+12,2.30108E+12,...,2.629330e+12,2.603340e+12,2.686480e+12,2.847440e+12,2.835930e+12,2.774530e+12,2.899920e+12,3.00628E+12,3.04663E+12,3.10569E+12

#### summary of the dataframe

In [16]:
accounts_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7592 entries, 0 to 7591
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ï»¿Series Name  7592 non-null   object
 1   Series Code     7592 non-null   object
 2   Country Name    7592 non-null   object
 3   Country Code    7592 non-null   object
 4   1995 [YR1995]   7592 non-null   object
 5   1996 [YR1996]   7592 non-null   object
 6   1997 [YR1997]   7592 non-null   object
 7   1998 [YR1998]   7592 non-null   object
 8   1999 [YR1999]   7592 non-null   object
 9   2000 [YR2000]   7592 non-null   object
 10  2001 [YR2001]   7592 non-null   object
 11  2002 [YR2002]   7592 non-null   object
 12  2003 [YR2003]   7592 non-null   object
 13  2004 [YR2004]   7592 non-null   object
 14  2005 [YR2005]   7592 non-null   float64
 15  2006 [YR2006]   7592 non-null   float64
 16  2007 [YR2007]   7592 non-null   float64
 17  2008 [YR2008]   7592 non-null   float64
 18  2009 [YR2009]   7592 non-null   float64
 19  2010 [YR2010]   7592 non-null   float64
 20  2011 [YR2011]   7592 non-null   float64
 21  2012 [YR2012]   7592 non-null   float64
 22  2013 [YR2013]   7592 non-null   float64
 23  2014 [YR2014]   7592 non-null   float64
 24  2015 [YR2015]   7592 non-null   float64
 25  2016 [YR2016]   7592 non-null   object
 26  2017 [YR2017]   7592 non-null   object
 27  2018 [YR2018]   7592 non-null   object
dtypes: float64(11), object(17)
memory usage: 1.6+ MB

#### viewing columns of the dataframe

In [17]:
accounts_data.columns

Index(['ï»¿Series Name', 'Series Code', 'Country Name', 'Country Code',
       '1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]',
       '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]',
       '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]',
       '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]',
       '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]',
       '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]'],
      dtype='object')

#### reanming columns of the dataframe

In [18]:
accounts_data.rename(columns = {'ï»¿Series Name':'indicator_name', 'Series Code':'indicator_code','Country Name':'country_name','Country Code':'country_code',
'1995 [YR1995]':'1995','1996 [YR1996]':'1996','1997 [YR1997]':'1997','1998 [YR1998]':'1998','1999 [YR1999]':'1999',
'2000 [YR2000]':'2000','2001 [YR2001]':'2001','2002 [YR2002]':'2002','2003 [YR2003]':'2003','2004 [YR2004]':'2004',
'2005 [YR2005]':'2005','2006 [YR2006]':'2006','2007 [YR2007]':'2007','2008 [YR2008]':'2008','2009 [YR2009]':'2009',
'2010 [YR2010]':'2010','2011 [YR2011]':'2011','2012 [YR2012]':'2012','2013 [YR2013]':'2013','2014 [YR2014]':'2014',
'2015 [YR2015]':'2015','2016 [YR2016]':'2016','2017 [YR2017]':'2017','2018 [YR2018]':'2018' }, inplace = True)
accounts_data.columns

Index(['indicator_name', 'indicator_code', 'country_name', 'country_code',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018'],
      dtype='object')

#### selecting certaing columns of the dataframe for the table 'accounts_data'

In [19]:
accounts_data_clean = accounts_data[['country_name','country_code','indicator_name','indicator_code','1995','2000','2010','2014']]
accounts_data_clean['1995'] = accounts_data_clean['1995'].replace(['..'], 0)
accounts_data_clean['2000'] = accounts_data_clean['2000'].replace(['..'], 0)
accounts_data_clean['2010'] = accounts_data_clean['2010'].replace(['..'], 0)
accounts_data_clean['2014'] = accounts_data_clean['2014'].replace(['..'], 0)
accounts_data_clean.head()

C:\Users\Vighnesh\AppData\Local\Temp\ipykernel_9920\1450180399.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accounts_data_clean['1995'] = accounts_data_clean['1995'].replace(['..'], 0)
C:\Users\Vighnesh\AppData\Local\Temp\ipykernel_9920\1450180399.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accounts_data_clean['2000'] = accounts_data_clean['2000'].replace(['..'], 0)
C:\Users\Vighnesh\AppData\Local\Temp\ipykernel_9920\1450180399.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accounts_data_clean['2010'] = accounts_data_clean['2010'].replace(['..'], 0)
C:\Users\Vighnesh\AppData\Local\Temp\ipykernel_9920\1450180399.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accounts_data_clean['2014'] = accounts_data_clean['2014'].replace(['..'], 0)

,country_name,country_code,indicator_name,indicator_code,1995,2000,2010,2014
0,Albania,ALB,Human capital (constant 2018 US$),NW.HCA.TO,44861001530,43611277219,6.805651e+10,7.248767e+10
1,Argentina,ARG,Human capital (constant 2018 US$),NW.HCA.TO,1.37855E+12,1.84136E+12,2.419210e+12,3.128110e+12
2,Armenia,ARM,Human capital (constant 2018 US$),NW.HCA.TO,31162180567,36048138201,6.083493e+10,7.320107e+10
3,Australia,AUS,Human capital (constant 2018 US$),NW.HCA.TO,5.65711E+12,6.58307E+12,9.242020e+12,1.093710e+13
4,Austria,AUT,Human capital (constant 2018 US$),NW.HCA.TO,2.22685E+12,2.30108E+12,2.603340e+12,2.774530e+12

### Read 'wealth-accountsSeries.csv' into pandas dataframe

In [20]:
accounts_series = pd.read_csv("data/wealth-accountsSeries.csv", encoding='cp1252')
accounts_series.head()

,ï»¿Code,Indicator Name,Long definition,Source,Topic,Unit of measure,Periodicity,Reference period,Statistical concept and methodology,Previous Indicator Code,Previous Indicator Name
0,NW.HCA.TO,Human capital (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
1,NW.HCA.PC,Human capital per capita (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
2,NW.HCA.FEMP.PC,"Human capital per capita, employed female (con...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
3,NW.HCA.MEMP.PC,"Human capital per capita, employed male (const...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
4,NW.HCA.FEMA.PC,"Human capital per capita, female (constant 201...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN

#### summary of the dataframe

In [21]:
accounts_series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ï»¿Code                              52 non-null     object
 1   Indicator Name                       52 non-null     object
 2   Long definition                      52 non-null     object
 3   Source                               52 non-null     object
 4   Topic                                52 non-null     object
 5   Unit of measure                      52 non-null     object
 6   Periodicity                          52 non-null     object
 7   Reference period                     52 non-null     object
 8   Statistical concept and methodology  52 non-null     object
 9   Previous Indicator Code              2 non-null      object
 10  Previous Indicator Name              2 non-null      object
dtypes: object(11)
memory usage: 4.6+ KB

#### renaming some columns the dataframe

In [22]:
accounts_series.rename(columns = {'ï»¿Code':'series_code', 'Indicator Name':'indicator_name', 'Topic':'topic'}, inplace = True)
accounts_series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   series_code                          52 non-null     object
 1   indicator_name                       52 non-null     object
 2   Long definition                      52 non-null     object
 3   Source                               52 non-null     object
 4   topic                                52 non-null     object
 5   Unit of measure                      52 non-null     object
 6   Periodicity                          52 non-null     object
 7   Reference period                     52 non-null     object
 8   Statistical concept and methodology  52 non-null     object
 9   Previous Indicator Code              2 non-null      object
 10  Previous Indicator Name              2 non-null      object
dtypes: object(11)
memory usage: 4.6+ KB

#### selecting some columns the dataframe

In [23]:
accounts_series_clean = accounts_series[['series_code','topic','indicator_name']]
accounts_series_clean.head()

,series_code,topic,indicator_name
0,NW.HCA.TO,Human capital,Human capital (constant 2018 US$)
1,NW.HCA.PC,Human capital,Human capital per capita (constant 2018 US$)
2,NW.HCA.FEMP.PC,Human capital,"Human capital per capita, employed female (con..."
3,NW.HCA.MEMP.PC,Human capital,"Human capital per capita, employed male (const..."
4,NW.HCA.FEMA.PC,Human capital,"Human capital per capita, female (constant 201..."

### Call fuction to connect to mysql cursor and get a cursor to execute queries

In [24]:
db_connection = connect_to_sql()
db_cursor = db_connection.cursor()

### Call function to create database 'accounts'

In [25]:
create_database(db_cursor)

Creating DATABASE - accounts

Showing all databases...
('Database',)
('accounts',)
('information_schema',)
('myfirstdb',)
('mysql',)
('performance_schema',)
('sakila',)
('sys',)

Using accounts

### Call function to create table 'accounts_country'

In [26]:
table = "accounts_country"
schema = "(country_code VARCHAR(5) PRIMARY KEY, short_name VARCHAR(50), table_name VARCHAR(50),	long_name VARCHAR(200), currency_unit VARCHAR(50))"
create_table(db_cursor,table,schema)

Creating TABLE - accounts_country
Showing all tables under accounts...
('Tables_in_accounts',)
('accounts_country',)
Showing 'accounts_country' Table schema  ...
('Field', 'Type', 'Null', 'Key', 'Default', 'Extra')
('country_code', 'varchar(5)', 'NO', 'PRI', None, '')
('short_name', 'varchar(50)', 'YES', '', None, '')
('table_name', 'varchar(50)', 'YES', '', None, '')
('long_name', 'varchar(200)', 'YES', '', None, '')
('currency_unit', 'varchar(50)', 'YES', '', None, '')

### Call function to create table 'accounts_data'

In [27]:
table = "accounts_data"
schema = "(country_name VARCHAR(50), country_code VARCHAR(5), indicator_name VARCHAR(200), indicator_code VARCHAR(50),	year_1995 BIGINT, year_2000 BIGINT,	year_2010 BIGINT, year_2014 BIGINT)"
create_table(db_cursor,table,schema)

Creating TABLE - accounts_data
Showing all tables under accounts...
('Tables_in_accounts',)
('accounts_country',)
('accounts_data',)
Showing 'accounts_data' Table schema  ...
('Field', 'Type', 'Null', 'Key', 'Default', 'Extra')
('country_name', 'varchar(50)', 'YES', '', None, '')
('country_code', 'varchar(5)', 'YES', '', None, '')
('indicator_name', 'varchar(200)', 'YES', '', None, '')
('indicator_code', 'varchar(50)', 'YES', '', None, '')
('year_1995', 'bigint', 'YES', '', None, '')
('year_2000', 'bigint', 'YES', '', None, '')
('year_2010', 'bigint', 'YES', '', None, '')
('year_2014', 'bigint', 'YES', '', None, '')

### Call function to create table 'accounts_series'

In [28]:
table = "accounts_series"
schema = "(series_code VARCHAR(20), topic VARCHAR(20), indicator_name VARCHAR(200))"
db_cursor = create_table(db_cursor,table,schema)

Creating TABLE - accounts_series
Showing all tables under accounts...
('Tables_in_accounts',)
('accounts_country',)
('accounts_data',)
('accounts_series',)
Showing 'accounts_series' Table schema  ...
('Field', 'Type', 'Null', 'Key', 'Default', 'Extra')
('series_code', 'varchar(20)', 'YES', '', None, '')
('topic', 'varchar(20)', 'YES', '', None, '')
('indicator_name', 'varchar(200)', 'YES', '', None, '')

### Insert records from 'accounts_country_clean' dataframe to 'accounts_country'

In [29]:
table = "accounts_country"
cols = "(country_code, short_name, table_name,	long_name, currency_unit)"
for index,row in accounts_country_clean.iterrows():
    record = (row[0],row[1],row[2],row[3],row[4])
    db_cursor = insert_table(db_cursor,table,cols,record)
db_cursor = show_all_records(db_cursor,table)

Inserting record ('ALB', 'Albania', 'Albania', 'Republic of Albania', 'Albanian lek') into table...

Inserting record ('ARG', 'Argentina', 'Argentina', 'Argentine Republic', 'Argentine peso') into table...

Inserting record ('ARM', 'Armenia', 'Armenia', 'Republic of Armenia', 'Armenian dram') into table...

Inserting record ('AUS', 'Australia', 'Australia', 'Commonwealth of Australia', 'Australian dollar') into table...

Inserting record ('AUT', 'Austria', 'Austria', 'Republic of Austria', 'Euro') into table...

Inserting record ('AZE', 'Azerbaijan', 'Azerbaijan', 'Republic of Azerbaijan', 'New Azeri manat') into table...

Inserting record ('BHR', 'Bahrain', 'Bahrain', 'Kingdom of Bahrain', 'Bahraini dinar') into table...

Inserting record ('BGD', 'Bangladesh', 'Bangladesh', "People's Republic of Bangladesh", 'Bangladeshi taka') into table...

Inserting record ('BLR', 'Belarus', 'Belarus', 'Republic of Belarus', 'Belarusian rubel') into table...

Inserting record ('BEL', 'Belgium', 'Belgium', 'Kingdom of Belgium', 'Euro') into table...

Inserting record ('BLZ', 'Belize', 'Belize', 'Belize', 'Belize dollar') into table...

Inserting record ('BEN', 'Benin', 'Benin', 'Republic of Benin', 'West African CFA franc') into table...

Inserting record ('BOL', 'Bolivia', 'Bolivia', 'Plurinational State of Bolivia', 'Bolivian Boliviano') into table...

Inserting record ('BIH', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark') into table...

Inserting record ('BWA', 'Botswana', 'Botswana', 'Republic of Botswana', 'Botswana pula') into table...

Inserting record ('BRA', 'Brazil', 'Brazil', 'Federative Republic of Brazil', 'Brazilian real') into table...

Inserting record ('BGR', 'Bulgaria', 'Bulgaria', 'Republic of Bulgaria', 'Bulgarian lev') into table...

Inserting record ('BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'West African CFA franc') into table...

Inserting record ('BDI', 'Burundi', 'Burundi', 'Republic of Burundi', 'Burundi franc') into table...

Inserting record ('KHM', 'Cambodia', 'Cambodia', 'Kingdom of Cambodia', 'Cambodian riel') into table...

Inserting record ('CMR', 'Cameroon', 'Cameroon', 'Republic of Cameroon', 'Central African CFA franc') into table...

Inserting record ('CAN', 'Canada', 'Canada', 'Canada', 'Canadian dollar') into table...

Inserting record ('CAF', 'Central African Republic', 'Central African Republic', 'Central African Republic', 'Central African CFA franc') into table...

Inserting record ('TCD', 'Chad', 'Chad', 'Republic of Chad', 'Central African CFA franc') into table...

Inserting record ('CHL', 'Chile', 'Chile', 'Republic of Chile', 'Chilean peso') into table...

Inserting record ('CHN', 'China', 'China', "People's Republic of China", 'Chinese yuan') into table...

Inserting record ('COL', 'Colombia', 'Colombia', 'Republic of Colombia', 'Colombian peso') into table...

Inserting record ('COM', 'Comoros', 'Comoros', 'Union of the Comoros', 'Comorian franc') into table...

Inserting record ('COG', 'Congo', 'Congo, Rep.', 'Republic of Congo', 'Central African CFA franc') into table...

Inserting record ('CRI', 'Costa Rica', 'Costa Rica', 'Republic of Costa Rica', 'Costa Rican colon') into table...

Inserting record ('CIV', "Côte d'Ivoire", "Côte d'Ivoire", "Republic of Côte d'Ivoire", 'West African CFA franc') into table...

Inserting record ('HRV', 'Croatia', 'Croatia', 'Republic of Croatia', 'Croatian kuna') into table...

Inserting record ('CZE', 'Czech Republic', 'Czech Republic', 'Czech Republic', 'Czech koruna') into table...

Inserting record ('COD', 'Dem. Rep. Congo', 'Congo, Dem. Rep.', 'Democratic Republic of the Congo', 'Congolese franc') into table...

Inserting record ('DNK', 'Denmark', 'Denmark', 'Kingdom of Denmark', 'Danish krone') into table...

Inserting record ('DJI', 'Djibouti', 'Djibouti', 'Republic of Djibouti', 'Djibouti franc') into table...

Inserting record ('DOM', 'Dominican Republic', 'Dominican Republic', 'Dominican Republic', 'Dominican peso') into table...

Inserting record ('ECU', 'Ecuador', 'Ecuador', 'Republic of Ecuador', 'U.S. dollar') into table...

Inserting record ('EGY', 'Egypt', 'Egypt, Arab Rep.', 'Arab Republic of Egypt', 'Egyptian pound') into table...

Inserting record ('SLV', 'El Salvador', 'El Salvador', 'Republic of El Salvador', 'U.S. dollar') into table...

Inserting record ('EST', 'Estonia', 'Estonia', 'Republic of Estonia', 'Euro') into table...

Inserting record ('SWZ', 'Eswatini', 'Eswatini', 'Kingdom of Eswatini', 'Swazi lilangeni') into table...

Inserting record ('ETH', 'Ethiopia', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'Ethiopian birr') into table...

Inserting record ('FIN', 'Finland', 'Finland', 'Republic of Finland', 'Euro') into table...

Inserting record ('FRA', 'France', 'France', 'French Republic', 'Euro') into table...

Inserting record ('GAB', 'Gabon', 'Gabon', 'Gabonese Republic', 'Central African CFA franc') into table...

Inserting record ('GEO', 'Georgia', 'Georgia', 'Georgia', 'Georgian lari') into table...

Inserting record ('DEU', 'Germany', 'Germany', 'Federal Republic of Germany', 'Euro') into table...

Inserting record ('GHA', 'Ghana', 'Ghana', 'Republic of Ghana', 'New Ghanaian cedi') into table...

Inserting record ('GRC', 'Greece', 'Greece', 'Hellenic Republic', 'Euro') into table...

Inserting record ('GTM', 'Guatemala', 'Guatemala', 'Republic of Guatemala', 'Guatemalan quetzal') into table...

Inserting record ('GIN', 'Guinea', 'Guinea', 'Republic of Guinea', 'Guinean franc') into table...

Inserting record ('GUY', 'Guyana', 'Guyana', 'Co-operative Republic of Guyana', 'Guyana dollar') into table...

Inserting record ('HTI', 'Haiti', 'Haiti', 'Republic of Haiti', 'Haitian gourde') into table...

Inserting record ('HND', 'Honduras', 'Honduras', 'Republic of Honduras', 'Honduran lempira') into table...

Inserting record ('HUN', 'Hungary', 'Hungary', 'Hungary', 'Hungarian forint') into table...

Inserting record ('ISL', 'Iceland', 'Iceland', 'Republic of Iceland', 'Iceland krona') into table...

Inserting record ('IND', 'India', 'India', 'Republic of India', 'Indian rupee') into table...

Inserting record ('IDN', 'Indonesia', 'Indonesia', 'Republic of Indonesia', 'Indonesian rupiah') into table...

Inserting record ('IRN', 'Iran', 'Iran, Islamic Rep.', 'Islamic Republic of Iran', 'Iranian rial') into table...

Inserting record ('IRQ', 'Iraq', 'Iraq', 'Republic of Iraq', 'Iraqi dinar') into table...

Inserting record ('IRL', 'Ireland', 'Ireland', 'Ireland', 'Euro') into table...

Inserting record ('ITA', 'Italy', 'Italy', 'Italian Republic', 'Euro') into table...

Inserting record ('JAM', 'Jamaica', 'Jamaica', 'Jamaica', 'Jamaican dollar') into table...

Inserting record ('JPN', 'Japan', 'Japan', 'Japan', 'Japanese yen') into table...

Inserting record ('JOR', 'Jordan', 'Jordan', 'Hashemite Kingdom of Jordan', 'Jordanian dinar') into table...

Inserting record ('KAZ', 'Kazakhstan', 'Kazakhstan', 'Republic of Kazakhstan', 'Kazakh tenge') into table...

Inserting record ('KEN', 'Kenya', 'Kenya', 'Republic of Kenya', 'Kenyan shilling') into table...

Inserting record ('KOR', 'Korea', 'Korea, Rep.', 'Republic of Korea', 'Korean won') into table...

Inserting record ('KWT', 'Kuwait', 'Kuwait', 'State of Kuwait', 'Kuwaiti dinar') into table...

Inserting record ('KGZ', 'Kyrgyz Republic', 'Kyrgyz Republic', 'Kyrgyz Republic', 'Kyrgyz som') into table...

Inserting record ('LAO', 'Lao PDR', 'Lao PDR', "Lao People's Democratic Republic", 'Lao kip') into table...

Inserting record ('LVA', 'Latvia', 'Latvia', 'Republic of Latvia', 'Euro') into table...

Inserting record ('LBN', 'Lebanon', 'Lebanon', 'Lebanese Republic', 'Lebanese pound') into table...

Inserting record ('LSO', 'Lesotho', 'Lesotho', 'Kingdom of Lesotho', 'Lesotho loti') into table...

Inserting record ('LBR', 'Liberia', 'Liberia', 'Republic of Liberia', 'U.S. dollar') into table...

Inserting record ('LTU', 'Lithuania', 'Lithuania', 'Republic of Lithuania', 'Euro') into table...

Inserting record ('LUX', 'Luxembourg', 'Luxembourg', 'Grand Duchy of Luxembourg', 'Euro') into table...

Inserting record ('MDG', 'Madagascar', 'Madagascar', 'Republic of Madagascar', 'Malagasy ariary') into table...

Inserting record ('MWI', 'Malawi', 'Malawi', 'Republic of Malawi', 'Malawi kwacha') into table...

Inserting record ('MYS', 'Malaysia', 'Malaysia', 'Malaysia', 'Malaysian ringgit') into table...

Inserting record ('MDV', 'Maldives', 'Maldives', 'Republic of Maldives', 'Maldivian rufiyaa') into table...

Inserting record ('MLI', 'Mali', 'Mali', 'Republic of Mali', 'West African CFA franc') into table...

Inserting record ('MLT', 'Malta', 'Malta', 'Republic of Malta', 'Euro') into table...

Inserting record ('MRT', 'Mauritania', 'Mauritania', 'Islamic Republic of Mauritania', 'Mauritanian ouguiya') into table...

Inserting record ('MUS', 'Mauritius', 'Mauritius', 'Republic of Mauritius', 'Mauritian rupee') into table...

Inserting record ('MEX', 'Mexico', 'Mexico', 'United Mexican States', 'Mexican peso') into table...

Inserting record ('MDA', 'Moldova', 'Moldova', 'Republic of Moldova', 'Moldovan leu') into table...

Inserting record ('MNG', 'Mongolia', 'Mongolia', 'Mongolia', 'Mongolian tugrik') into table...

Inserting record ('MAR', 'Morocco', 'Morocco', 'Kingdom of Morocco', 'Moroccan dirham') into table...

Inserting record ('MOZ', 'Mozambique', 'Mozambique', 'Republic of Mozambique', 'New Mozambican metical') into table...

Inserting record ('NAM', 'Namibia', 'Namibia', 'Republic of Namibia', 'Namibian dollar') into table...

Inserting record ('NPL', 'Nepal', 'Nepal', 'Nepal', 'Nepalese rupee') into table...

Inserting record ('NLD', 'Netherlands', 'Netherlands', 'Kingdom of the Netherlands', 'Euro') into table...

Inserting record ('NIC', 'Nicaragua', 'Nicaragua', 'Republic of Nicaragua', 'Nicaraguan gold cordoba') into table...

Inserting record ('NER', 'Niger', 'Niger', 'Republic of Niger', 'West African CFA franc') into table...

Inserting record ('NGA', 'Nigeria', 'Nigeria', 'Federal Republic of Nigeria', 'Nigerian naira') into table...

Inserting record ('MKD', 'North Macedonia', 'North Macedonia', 'Republic of North Macedonia', 'Macedonian denar') into table...

Inserting record ('NOR', 'Norway', 'Norway', 'Kingdom of Norway', 'Norwegian krone') into table...

Inserting record ('OMN', 'Oman', 'Oman', 'Sultanate of Oman', 'Omani rial') into table...

Inserting record ('PAK', 'Pakistan', 'Pakistan', 'Islamic Republic of Pakistan', 'Pakistani rupee') into table...

Inserting record ('PAN', 'Panama', 'Panama', 'Republic of Panama', 'Panamanian balboa') into table...

Inserting record ('PNG', 'Papua New Guinea', 'Papua New Guinea', 'The Independent State of Papua New Guinea', 'Papua New Guinea kina') into table...

Inserting record ('PRY', 'Paraguay', 'Paraguay', 'Republic of Paraguay', 'Paraguayan guarani') into table...

Inserting record ('PER', 'Peru', 'Peru', 'Republic of Peru', 'Peruvian new sol') into table...

Inserting record ('PHL', 'Philippines', 'Philippines', 'Republic of the Philippines', 'Philippine peso') into table...

Inserting record ('POL', 'Poland', 'Poland', 'Republic of Poland', 'Polish zloty') into table...

Inserting record ('PRT', 'Portugal', 'Portugal', 'Portuguese Republic', 'Euro') into table...

Inserting record ('QAT', 'Qatar', 'Qatar', 'State of Qatar', 'Qatari riyal') into table...

Inserting record ('ROU', 'Romania', 'Romania', 'Romania', 'New Romanian leu') into table...

Inserting record ('RUS', 'Russia', 'Russian Federation', 'Russian Federation', 'Russian ruble') into table...

Inserting record ('RWA', 'Rwanda', 'Rwanda', 'Republic of Rwanda', 'Rwandan franc') into table...

Inserting record ('SAU', 'Saudi Arabia', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'Saudi Arabian riyal') into table...

Inserting record ('SEN', 'Senegal', 'Senegal', 'Republic of Senegal', 'West African CFA franc') into table...

Inserting record ('SLE', 'Sierra Leone', 'Sierra Leone', 'Republic of Sierra Leone', 'Sierra Leonean leone') into table...

Inserting record ('SGP', 'Singapore', 'Singapore', 'Republic of Singapore', 'Singapore dollar') into table...

Inserting record ('SVK', 'Slovak Republic', 'Slovak Republic', 'Slovak Republic', 'Euro') into table...

Inserting record ('SVN', 'Slovenia', 'Slovenia', 'Republic of Slovenia', 'Euro') into table...

Inserting record ('SLB', 'Solomon Islands', 'Solomon Islands', 'Solomon Islands', 'Solomon Islands dollar') into table...

Inserting record ('ZAF', 'South Africa', 'South Africa', 'Republic of South Africa', 'South African rand') into table...

Inserting record ('ESP', 'Spain', 'Spain', 'Kingdom of Spain', 'Euro') into table...

Inserting record ('LKA', 'Sri Lanka', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'Sri Lankan rupee') into table...

Inserting record ('SUR', 'Suriname', 'Suriname', 'Republic of Suriname', 'Suriname dollar') into table...

Inserting record ('SWE', 'Sweden', 'Sweden', 'Kingdom of Sweden', 'Swedish krona') into table...

Inserting record ('CHE', 'Switzerland', 'Switzerland', 'Switzerland', 'Swiss franc') into table...

Inserting record ('TJK', 'Tajikistan', 'Tajikistan', 'Republic of Tajikistan', 'Tajik somoni') into table...

Inserting record ('TZA', 'Tanzania', 'Tanzania', 'United Republic of Tanzania', 'Tanzanian shilling') into table...

Inserting record ('THA', 'Thailand', 'Thailand', 'Kingdom of Thailand', 'Thai baht') into table...

Inserting record ('GMB', 'The Gambia', 'Gambia, The', 'Republic of The Gambia', 'Gambian dalasi') into table...

Inserting record ('TGO', 'Togo', 'Togo', 'Republic of Togo', 'West African CFA franc') into table...

Inserting record ('TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'Trinidad and Tobago dollar') into table...

Inserting record ('TUN', 'Tunisia', 'Tunisia', 'Republic of Tunisia', 'Tunisian dinar') into table...

Inserting record ('TUR', 'Turkey', 'Turkey', 'Republic of Turkey', 'New Turkish lira') into table...

Inserting record ('TKM', 'Turkmenistan', 'Turkmenistan', 'Turkmenistan', 'New Turkmen manat') into table...

Inserting record ('UGA', 'Uganda', 'Uganda', 'Republic of Uganda', 'Ugandan shilling') into table...

Inserting record ('UKR', 'Ukraine', 'Ukraine', 'Ukraine', 'Ukrainian hryvnia') into table...

Inserting record ('ARE', 'United Arab Emirates', 'United Arab Emirates', 'United Arab Emirates', 'U.A.E. dirham') into table...

Inserting record ('GBR', 'United Kingdom', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'Pound sterling') into table...

Inserting record ('USA', 'United States', 'United States', 'United States of America', 'U.S. dollar') into table...

Inserting record ('URY', 'Uruguay', 'Uruguay', 'Oriental Republic of Uruguay', 'Uruguayan peso') into table...

Inserting record ('VEN', 'Venezuela', 'Venezuela, RB', 'República Bolivariana de Venezuela', 'Venezuelan bolivar fuerte') into table...

Inserting record ('VNM', 'Vietnam', 'Vietnam', 'Socialist Republic of Vietnam', 'Vietnamese dong') into table...

Inserting record ('PSE', 'West Bank and Gaza', 'West Bank and Gaza', 'West Bank and Gaza', 'Israeli new shekel') into table...

Inserting record ('YEM', 'Yemen', 'Yemen, Rep.', 'Republic of Yemen', 'Yemeni rial') into table...

Inserting record ('ZMB', 'Zambia', 'Zambia', 'Republic of Zambia', 'New Zambian kwacha') into table...

Inserting record ('ZWE', 'Zimbabwe', 'Zimbabwe', 'Republic of Zimbabwe', 'U.S. dollar') into table...

Printing records from table...

('country_code', 'short_name', 'table_name', 'long_name', 'currency_unit')
('ALB', 'Albania', 'Albania', 'Republic of Albania', 'Albanian lek')
('ARE', 'United Arab Emirates', 'United Arab Emirates', 'United Arab Emirates', 'U.A.E. dirham')
('ARG', 'Argentina', 'Argentina', 'Argentine Republic', 'Argentine peso')
('ARM', 'Armenia', 'Armenia', 'Republic of Armenia', 'Armenian dram')
('AUS', 'Australia', 'Australia', 'Commonwealth of Australia', 'Australian dollar')
('AUT', 'Austria', 'Austria', 'Republic of Austria', 'Euro')
('AZE', 'Azerbaijan', 'Azerbaijan', 'Republic of Azerbaijan', 'New Azeri manat')
('BDI', 'Burundi', 'Burundi', 'Republic of Burundi', 'Burundi franc')
('BEL', 'Belgium', 'Belgium', 'Kingdom of Belgium', 'Euro')
('BEN', 'Benin', 'Benin', 'Republic of Benin', 'West African CFA franc')
('BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'West African CFA franc')
('BGD', 'Bangladesh', 'Bangladesh', "People's Republic of Bangladesh", 'Bangladeshi taka')
('BGR', 'Bulgaria', 'Bulgaria', 'Republic of Bulgaria', 'Bulgarian lev')
('BHR', 'Bahrain', 'Bahrain', 'Kingdom of Bahrain', 'Bahraini dinar')
('BIH', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark')
('BLR', 'Belarus', 'Belarus', 'Republic of Belarus', 'Belarusian rubel')
('BLZ', 'Belize', 'Belize', 'Belize', 'Belize dollar')
('BOL', 'Bolivia', 'Bolivia', 'Plurinational State of Bolivia', 'Bolivian Boliviano')
('BRA', 'Brazil', 'Brazil', 'Federative Republic of Brazil', 'Brazilian real')
('BWA', 'Botswana', 'Botswana', 'Republic of Botswana', 'Botswana pula')
('CAF', 'Central African Republic', 'Central African Republic', 'Central African Republic', 'Central African CFA franc')
('CAN', 'Canada', 'Canada', 'Canada', 'Canadian dollar')
('CHE', 'Switzerland', 'Switzerland', 'Switzerland', 'Swiss franc')
('CHL', 'Chile', 'Chile', 'Republic of Chile', 'Chilean peso')
('CHN', 'China', 'China', "People's Republic of China", 'Chinese yuan')
('CIV', "Côte d'Ivoire", "Côte d'Ivoire", "Republic of Côte d'Ivoire", 'West African CFA franc')
('CMR', 'Cameroon', 'Cameroon', 'Republic of Cameroon', 'Central African CFA franc')
('COD', 'Dem. Rep. Congo', 'Congo, Dem. Rep.', 'Democratic Republic of the Congo', 'Congolese franc')
('COG', 'Congo', 'Congo, Rep.', 'Republic of Congo', 'Central African CFA franc')
('COL', 'Colombia', 'Colombia', 'Republic of Colombia', 'Colombian peso')
('COM', 'Comoros', 'Comoros', 'Union of the Comoros', 'Comorian franc')
('CRI', 'Costa Rica', 'Costa Rica', 'Republic of Costa Rica', 'Costa Rican colon')
('CZE', 'Czech Republic', 'Czech Republic', 'Czech Republic', 'Czech koruna')
('DEU', 'Germany', 'Germany', 'Federal Republic of Germany', 'Euro')
('DJI', 'Djibouti', 'Djibouti', 'Republic of Djibouti', 'Djibouti franc')
('DNK', 'Denmark', 'Denmark', 'Kingdom of Denmark', 'Danish krone')
('DOM', 'Dominican Republic', 'Dominican Republic', 'Dominican Republic', 'Dominican peso')
('ECU', 'Ecuador', 'Ecuador', 'Republic of Ecuador', 'U.S. dollar')
('EGY', 'Egypt', 'Egypt, Arab Rep.', 'Arab Republic of Egypt', 'Egyptian pound')
('ESP', 'Spain', 'Spain', 'Kingdom of Spain', 'Euro')
('EST', 'Estonia', 'Estonia', 'Republic of Estonia', 'Euro')
('ETH', 'Ethiopia', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'Ethiopian birr')
('FIN', 'Finland', 'Finland', 'Republic of Finland', 'Euro')
('FRA', 'France', 'France', 'French Republic', 'Euro')
('GAB', 'Gabon', 'Gabon', 'Gabonese Republic', 'Central African CFA franc')
('GBR', 'United Kingdom', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'Pound sterling')
('GEO', 'Georgia', 'Georgia', 'Georgia', 'Georgian lari')
('GHA', 'Ghana', 'Ghana', 'Republic of Ghana', 'New Ghanaian cedi')
('GIN', 'Guinea', 'Guinea', 'Republic of Guinea', 'Guinean franc')
('GMB', 'The Gambia', 'Gambia, The', 'Republic of The Gambia', 'Gambian dalasi')
('GRC', 'Greece', 'Greece', 'Hellenic Republic', 'Euro')
('GTM', 'Guatemala', 'Guatemala', 'Republic of Guatemala', 'Guatemalan quetzal')
('GUY', 'Guyana', 'Guyana', 'Co-operative Republic of Guyana', 'Guyana dollar')
('HND', 'Honduras', 'Honduras', 'Republic of Honduras', 'Honduran lempira')
('HRV', 'Croatia', 'Croatia', 'Republic of Croatia', 'Croatian kuna')

### Insert records from 'accounts_data_clean' dataframe to 'accounts_data'

In [30]:
table = "accounts_data"
cols = "(country_name, country_code, indicator_name, indicator_code, year_1995, year_2000,	year_2010, year_2014)"
for index,row in accounts_data_clean.iterrows():
    record = (row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7])
    db_cursor = insert_table(db_cursor,table,cols,record)
        
db_cursor = show_all_records(db_cursor,table)

Inserting record ('Albania', 'ALB', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '44861001530', '43611277219', 68056509547.0, 72487665594.0) into table...

Inserting record ('Argentina', 'ARG', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.37855E+12', '1.84136E+12', 2419210000000.0, 3128110000000.0) into table...

Inserting record ('Armenia', 'ARM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '31162180567', '36048138201', 60834929642.0, 73201068526.0) into table...

Inserting record ('Australia', 'AUS', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '5.65711E+12', '6.58307E+12', 9242020000000.0, 10937100000000.0) into table...

Inserting record ('Austria', 'AUT', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.22685E+12', '2.30108E+12', 2603340000000.0, 2774530000000.0) into table...

Inserting record ('Azerbaijan', 'AZE', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '27450086133', '30684089751', 68530441552.0, 78910540804.0) into table...

Inserting record ('Bahrain', 'BHR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '59424574700', '64225918195', 110600000000.0, 124676000000.0) into table...

Inserting record ('Bangladesh', 'BGD', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '6.65132E+11', '8.25308E+11', 1256090000000.0, 1588910000000.0) into table...

Inserting record ('Belarus', 'BLR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.35923E+11', '1.87347E+11', 376500000000.0, 422856000000.0) into table...

Inserting record ('Belgium', 'BEL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.50305E+12', '2.77027E+12', 3269440000000.0, 3531400000000.0) into table...

Inserting record ('Belize', 'BLZ', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3626734202', '4949155430', 6823042492.0, 7348016610.0) into table...

Inserting record ('Benin', 'BEN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '53114355216', '67560411651', 100530000000.0, 124790000000.0) into table...

Inserting record ('Bolivia', 'BOL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.34192E+11', '1.66855E+11', 174748000000.0, 225210000000.0) into table...

Inserting record ('Bosnia and Herzegovina', 'BIH', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '14212640229', '51901692825', 79016302067.0, 78354467453.0) into table...

Inserting record ('Botswana', 'BWA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '45214352409', '38891632985', 64090618674.0, 84818697871.0) into table...

Inserting record ('Brazil', 'BRA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.02896E+13', '1.11812E+13', 14992900000000.0, 16477000000000.0) into table...

Inserting record ('Bulgaria', 'BGR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.06151E+11', '2.21756E+11', 324541000000.0, 349891000000.0) into table...

Inserting record ('Burkina Faso', 'BFA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '37639657433', '39534583381', 55492316648.0, 69378175505.0) into table...

Inserting record ('Burundi', 'BDI', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '25260614713', '26369177587', 34914211534.0, 40359352125.0) into table...

Inserting record ('Cambodia', 'KHM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '31552193558', '45572304089', 105571000000.0, 143184000000.0) into table...

Inserting record ('Cameroon', 'CMR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.35811E+11', '1.58259E+11', 239663000000.0, 289177000000.0) into table...

Inserting record ('Canada', 'CAN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.24612E+13', '1.34798E+13', 17059700000000.0, 18431500000000.0) into table...

Inserting record ('Central African Republic', 'CAF', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '4664238686', '4834082666', 4871660896.0, 3653548520.0) into table...

Inserting record ('Chad', 'TCD', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '20035438013', '25976956913', 48298512617.0, 68524112338.0) into table...

Inserting record ('Chile', 'CHL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '8.2275E+11', '1.11235E+12', 1654980000000.0, 1919890000000.0) into table...

Inserting record ('China', 'CHN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.07911E+13', '4.55266E+13', 101797000000000.0, 140072000000000.0) into table...

Inserting record ('Colombia', 'COL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.26371E+12', '1.28861E+12', 2103380000000.0, 2611930000000.0) into table...

Inserting record ('Comoros', 'COM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '4338612860', '5261481829', 6411014797.0, 7305471287.0) into table...

Inserting record ('Congo', 'COG', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '51818637694', '47061739092', 71958554452.0, 84816292956.0) into table...

Inserting record ('Costa Rica', 'CRI', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.70079E+11', '2.16749E+11', 404258000000.0, 471337000000.0) into table...

Inserting record ("CÃ´te d'Ivoire", 'CIV', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.49818E+11', '1.7997E+11', 185046000000.0, 202583000000.0) into table...

Inserting record ('Croatia', 'HRV', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.13742E+11', '2.72701E+11', 326370000000.0, 285977000000.0) into table...

Inserting record ('Czech Republic', 'CZE', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '7.96148E+11', '8.48691E+11', 1156160000000.0, 1305120000000.0) into table...

Inserting record ('Dem. Rep. Congo', 'COD', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.75277E+11', '1.42396E+11', 211708000000.0, 287607000000.0) into table...

Inserting record ('Denmark', 'DNK', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.84088E+12', '1.97327E+12', 2235360000000.0, 2205820000000.0) into table...

Inserting record ('Djibouti', 'DJI', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3277237104', '3159249089', 5491623326.0, 10118589010.0) into table...

Inserting record ('Dominican Republic', 'DOM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.45543E+11', '3.03468E+11', 343446000000.0, 448664000000.0) into table...

Inserting record ('Ecuador', 'ECU', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.99301E+11', '4.31744E+11', 886128000000.0, 1021810000000.0) into table...

Inserting record ('Egypt', 'EGY', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '5.27839E+11', '7.09523E+11', 957566000000.0, 1129870000000.0) into table...

Inserting record ('El Salvador', 'SLV', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '80286769162', '1.18309E+11', 136389000000.0, 145566000000.0) into table...

Inserting record ('Estonia', 'EST', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '86109359726', '1.07184E+11', 147504000000.0, 171546000000.0) into table...

Inserting record ('Eswatini', 'SWZ', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '17679559574', '17180011535', 25523247388.0, 30868503452.0) into table...

Inserting record ('Ethiopia', 'ETH', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.19885E+11', '1.53163E+11', 362499000000.0, 550960000000.0) into table...

Inserting record ('Finland', 'FIN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.17827E+12', '1.402E+12', 1781710000000.0, 1903820000000.0) into table...

Inserting record ('France', 'FRA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.62303E+13', '1.81128E+13', 20029600000000.0, 21074400000000.0) into table...

Inserting record ('Gabon', 'GAB', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '30344773782', '28607484407', 29479340576.0, 37759373091.0) into table...

Inserting record ('Georgia', 'GEO', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '27130393819', '32092443366', 39134329395.0, 61797713689.0) into table...

Inserting record ('Germany', 'DEU', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.20575E+13', '2.27697E+13', 25862400000000.0, 29574800000000.0) into table...

Inserting record ('Ghana', 'GHA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.45336E+11', '1.74828E+11', 312547000000.0, 427955000000.0) into table...

Inserting record ('Greece', 'GRC', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '8.68829E+11', '1.0647E+12', 1284920000000.0, 875827000000.0) into table...

Inserting record ('Guatemala', 'GTM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.11779E+11', '2.59924E+11', 311582000000.0, 358091000000.0) into table...

Inserting record ('Guinea', 'GIN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3104155404', '3321494303', 4833752157.0, 6401954712.0) into table...

Inserting record ('Guyana', 'GUY', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '10734007159', '12071542011', 14264848737.0, 17352850925.0) into table...

Inserting record ('Haiti', 'HTI', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '41246945989', '47946440986', 41937287177.0, 48822730552.0) into table...

Inserting record ('Honduras', 'HND', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '68278678364', '89518666859', 166042000000.0, 161987000000.0) into table...

Inserting record ('Hungary', 'HUN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '5.38004E+11', '5.9455E+11', 761604000000.0, 836409000000.0) into table...

Inserting record ('Iceland', 'ISL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.37237E+11', '1.64362E+11', 171275000000.0, 172898000000.0) into table...

Inserting record ('India', 'IND', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '5.75865E+12', '7.62098E+12', 12930900000000.0, 16375000000000.0) into table...

Inserting record ('Indonesia', 'IDN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.61901E+12', '3.21349E+12', 6074730000000.0, 6045010000000.0) into table...

Inserting record ('Iran', 'IRN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.38886E+12', '1.50793E+12', 1816240000000.0, 1799750000000.0) into table...

Inserting record ('Iraq', 'IRQ', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '93925276889', '85077592795', 429981000000.0, 561504000000.0) into table...

Inserting record ('Ireland', 'IRL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '9.47469E+11', '1.23767E+12', 1468110000000.0, 1435510000000.0) into table...

Inserting record ('Italy', 'ITA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.07285E+13', '1.09007E+13', 11827000000000.0, 10854200000000.0) into table...

Inserting record ('Jamaica', 'JAM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '82161366115', '84546061124', 97459969340.0, 99013628923.0) into table...

Inserting record ('Japan', 'JPN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.99396E+13', '4.0776E+13', 35916300000000.0, 37073600000000.0) into table...

Inserting record ('Jordan', 'JOR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '83185064661', '95518891203', 168155000000.0, 163817000000.0) into table...

Inserting record ('Kazakhstan', 'KAZ', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.9402E+11', '3.73189E+11', 748417000000.0, 843516000000.0) into table...

Inserting record ('Kenya', 'KEN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.66254E+11', '2.73985E+11', 456771000000.0, 600936000000.0) into table...

Inserting record ('Korea', 'KOR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '4.31812E+12', '4.90835E+12', 7786060000000.0, 9114380000000.0) into table...

Inserting record ('Kuwait', 'KWT', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.20798E+11', '2.91267E+11', 478470000000.0, 499605000000.0) into table...

Inserting record ('Kyrgyz Republic', 'KGZ', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '19797845172', '21564159838', 26561981178.0, 30466205421.0) into table...

Inserting record ('Lao PDR', 'LAO', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '38955256382', '54486194614', 102806000000.0, 133368000000.0) into table...

Inserting record ('Latvia', 'LVA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '82828648282', '99687859703', 143112000000.0, 175878000000.0) into table...

Inserting record ('Lebanon', 'LBN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.17731E+11', '1.40549E+11', 214161000000.0, 240532000000.0) into table...

Inserting record ('Lesotho', 'LSO', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '14747433717', '13367713229', 15612014291.0, 19242741868.0) into table...

Inserting record ('Liberia', 'LBR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '9232610388', '15872474374', 14257398509.0, 21818833458.0) into table...

Inserting record ('Lithuania', 'LTU', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.3235E+11', '1.72563E+11', 221755000000.0, 266106000000.0) into table...

Inserting record ('Luxembourg', 'LUX', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.72513E+11', '1.99472E+11', 234144000000.0, 266305000000.0) into table...

Inserting record ('Madagascar', 'MDG', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '52813807974', '59480072120', 94187647041.0, 105019000000.0) into table...

Inserting record ('Malawi', 'MWI', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '21764883417', '25743162981', 43730231011.0, 49199013846.0) into table...

Inserting record ('Malaysia', 'MYS', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.19135E+12', '1.40773E+12', 2517100000000.0, 3205490000000.0) into table...

Inserting record ('Maldives', 'MDV', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '5643641742', '8059438735', 13093528065.0, 15666101633.0) into table...

Inserting record ('Mali', 'MLI', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '25729177497', '31919597228', 54963709227.0, 62802193340.0) into table...

Inserting record ('Malta', 'MLT', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '41371802031', '52495717474', 57256524939.0, 76257291940.0) into table...

Inserting record ('Mauritania', 'MRT', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '27176950572', '30658189922', 33139880441.0, 37317053154.0) into table...

Inserting record ('Mauritius', 'MUS', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '38710450906', '48709804473', 48959696449.0, 54383945111.0) into table...

Inserting record ('Mexico', 'MEX', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.76519E+12', '4.81611E+12', 5146440000000.0, 5586930000000.0) into table...

Inserting record ('Moldova', 'MDA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '9090721455', '7514217771', 14712758253.0, 16396181167.0) into table...

Inserting record ('Mongolia', 'MNG', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '22283604983', '23221056902', 34989423358.0, 56682293440.0) into table...

Inserting record ('Morocco', 'MAR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.29865E+11', '2.60472E+11', 400858000000.0, 463390000000.0) into table...

Inserting record ('Mozambique', 'MOZ', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '19306276468', '27086085630', 63691034895.0, 84656705470.0) into table...

Inserting record ('Namibia', 'NAM', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '56823230899', '58570714390', 88066147277.0, 115663000000.0) into table...

Inserting record ('Nepal', 'NPL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.05627E+11', '1.30683E+11', 134002000000.0, 155874000000.0) into table...

Inserting record ('Netherlands', 'NLD', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '4.66045E+12', '5.45931E+12', 6259740000000.0, 6344260000000.0) into table...

Inserting record ('Nicaragua', 'NIC', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '37313127612', '43715313828', 63363968368.0, 77067067662.0) into table...

Inserting record ('Niger', 'NER', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '32326679844', '36597550918', 55432644040.0, 49022802051.0) into table...

Inserting record ('Nigeria', 'NGA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '7.43258E+11', '6.95351E+11', 2978510000000.0, 3556060000000.0) into table...

Inserting record ('North Macedonia', 'MKD', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '59800374031', '53253986876', 59839736718.0, 60356119792.0) into table...

Inserting record ('Norway', 'NOR', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.37053E+12', '2.46574E+12', 2763120000000.0, 3090070000000.0) into table...

Inserting record ('Oman', 'OMN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.77046E+11', '1.769E+11', 266108000000.0, 330100000000.0) into table...

Inserting record ('Pakistan', 'PAK', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '9.44792E+11', '1.08989E+12', 1763420000000.0, 1996230000000.0) into table...

Inserting record ('Panama', 'PAN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.22878E+11', '1.78644E+11', 235596000000.0, 268962000000.0) into table...

Inserting record ('Papua New Guinea', 'PNG', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '68775030659', '63106429010', 88042657792.0, 110884000000.0) into table...

Inserting record ('Paraguay', 'PRY', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.49785E+11', '2.00361E+11', 263388000000.0, 360606000000.0) into table...

Inserting record ('Peru', 'PER', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '4.51457E+11', '4.75053E+11', 1070180000000.0, 1416360000000.0) into table...

Inserting record ('Philippines', 'PHL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.15954E+12', '1.21367E+12', 1774050000000.0, 2048080000000.0) into table...

Inserting record ('Poland', 'POL', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.56963E+12', '2.1277E+12', 3115460000000.0, 3125100000000.0) into table...

Inserting record ('Portugal', 'PRT', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.49568E+12', '1.82325E+12', 1816310000000.0, 1367040000000.0) into table...

Inserting record ('Qatar', 'QAT', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '61110737296', '1.103E+11', 418028000000.0, 523583000000.0) into table...

Inserting record ('Romania', 'ROU', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '8.11763E+11', '8.02053E+11', 1061730000000.0, 1104600000000.0) into table...

Inserting record ('Russia', 'RUS', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '3.47788E+12', '3.61106E+12', 7350380000000.0, 8990570000000.0) into table...

Inserting record ('Rwanda', 'RWA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '13267258123', '23748824677', 52942131341.0, 68755435422.0) into table...

Inserting record ('Saudi Arabia', 'SAU', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.91796E+12', '1.74618E+12', 1996530000000.0, 2357980000000.0) into table...

Inserting record ('Senegal', 'SEN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '44557170402', '59416105050', 91954686252.0, 106428000000.0) into table...

Inserting record ('Sierra Leone', 'SLE', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '9435572506', '12286016043', 20867084172.0, 32441667303.0) into table...

Inserting record ('Singapore', 'SGP', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '9.11031E+11', '1.19482E+12', 1942160000000.0, 2318600000000.0) into table...

Inserting record ('Slovak Republic', 'SVK', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.75764E+11', '3.56007E+11', 589921000000.0, 613522000000.0) into table...

Inserting record ('Slovenia', 'SVN', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '2.67711E+11', '3.01095E+11', 395839000000.0, 342672000000.0) into table...

Inserting record ('Solomon Islands', 'SLB', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '7161943960', '6231983830', 7910917673.0, 10489498394.0) into table...

Inserting record ('South Africa', 'ZAF', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '1.19912E+12', '1.22136E+12', 1673350000000.0, 1989490000000.0) into table...

Inserting record ('Spain', 'ESP', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '7.35561E+12', '8.80332E+12', 9745250000000.0, 8381960000000.0) into table...

Inserting record ('Sri Lanka', 'LKA', 'Human capital (constant 2018 US$)', 'NW.HCA.TO', '88445258433', '1.06409E+11', 200408000000.0, 257512000000.0) into table...


### Insert records from 'accounts_series_clean' dataframe to 'accounts_series'

In [31]:
table = "accounts_series"
cols = "(series_code, topic, indicator_name)"
for index,row in accounts_series_clean.iterrows():
    record = (row[0],row[1],row[2])
    db_cursor = insert_table(db_cursor,table,cols,record)
db_cursor = show_all_records(db_cursor,table)

Inserting record ('NW.HCA.TO', 'Human capital', 'Human capital (constant 2018 US$)') into table...

Inserting record ('NW.HCA.PC', 'Human capital', 'Human capital per capita (constant 2018 US$)') into table...

Inserting record ('NW.HCA.FEMP.PC', 'Human capital', 'Human capital per capita, employed female (constant 2018 US$)') into table...

Inserting record ('NW.HCA.MEMP.PC', 'Human capital', 'Human capital per capita, employed male (constant 2018 US$)') into table...

Inserting record ('NW.HCA.FEMA.PC', 'Human capital', 'Human capital per capita, female (constant 2018 US$)') into table...

Inserting record ('NW.HCA.MALE.PC', 'Human capital', 'Human capital per capita, male (constant 2018 US$)') into table...

Inserting record ('NW.HCA.FSEM.PC', 'Human capital', 'Human capital per capita, self-employed female (constant 2018 US$)') into table...

Inserting record ('NW.HCA.MSEM.PC', 'Human capital', 'Human capital per capita, self-employed male (constant 2018 US$)') into table...

Inserting record ('NW.HCA.FEMP.TO', 'Human capital', 'Human capital, employed female (constant 2018 US$)') into table...

Inserting record ('NW.HCA.MEMP.TO', 'Human capital', 'Human capital, employed male (constant 2018 US$)') into table...

Inserting record ('NW.HCA.FEMA.TO', 'Human capital', 'Human capital, female (constant 2018 US$)') into table...

Inserting record ('NW.HCA.MALE.TO', 'Human capital', 'Human capital, male (constant 2018 US$)') into table...

Inserting record ('NW.HCA.FSEM.TO', 'Human capital', 'Human capital, self-employed female (constant 2018 US$)') into table...

Inserting record ('NW.HCA.MSEM.TO', 'Human capital', 'Human capital, self-employed male (constant 2018 US$)') into table...

Inserting record ('NW.NCA.TO', 'Natural capital', 'Natural capital (constant 2018 US$)') into table...

Inserting record ('NW.NCA.PC', 'Natural capital', 'Natural capital per capita (constant 2018 US$)') into table...

Inserting record ('NW.NCA.AGRI.PC', 'Natural capital', 'Natural capital per capita, agricultural land (constant 2018 US$)') into table...

Inserting record ('NW.NCA.CROL.PC', 'Natural capital', 'Natural capital per capita, agricultural land: cropland (constant 2018 US$)') into table...

Inserting record ('NW.NCA.PASL.PC', 'Natural capital', 'Natural capital per capita, agricultural land: pastureland (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FISH.PC', 'Natural capital', 'Natural capital per capita, fisheries (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FECO.PC', 'Natural capital', 'Natural capital per capita, forests: ecosystem services (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FTIM.PC', 'Natural capital', 'Natural capital per capita, forests: timber (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FOSL.PC', 'Natural capital', 'Natural capital per capita, fossil fuels (constant 2018 US$)') into table...

Inserting record ('NW.NCA.MANG.PC', 'Natural capital', 'Natural capital per capita, mangroves (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SSOI.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SACO.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: coal (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SAGA.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: gas (constant 2018 US$)') into table...

Inserting record ('NW.NCA.MINR.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: minerals (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SAOI.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: oil (constant 2018 US$)') into table...

Inserting record ('NW.NCA.PRAR.PC', 'Natural capital', 'Natural capital per capita, protected areas (constant 2018 US$)') into table...

Inserting record ('NW.NCA.RNEW.PC', 'Natural capital', 'Natural capital per capita, renewable (constant 2018 US$)') into table...

Inserting record ('NW.NCA.AGRI.TO', 'Natural capital', 'Natural capital, agricultural land (constant 2018 US$)') into table...

Inserting record ('NW.NCA.CROL.TO', 'Natural capital', 'Natural capital, agricultural land: cropland (constant 2018 US$)') into table...

Inserting record ('NW.NCA.PASL.TO', 'Natural capital', 'Natural capital, agricultural land: pastureland (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FISH.TO', 'Natural capital', 'Natural capital, fisheries (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FECO.TO', 'Natural capital', 'Natural capital, forests: ecosystem services (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FTIM.TO', 'Natural capital', 'Natural capital, forests: timber (constant 2018 US$)') into table...

Inserting record ('NW.NCA.FOSL.TO', 'Natural capital', 'Natural capital, fossil fuels (constant 2018 US$)') into table...

Inserting record ('NW.NCA.MANG.TO', 'Natural capital', 'Natural capital, mangroves (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SSOI.TO', 'Natural capital', 'Natural capital, nonrenewable assets (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SACO.TO', 'Natural capital', 'Natural capital, nonrenewable assets: coal (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SAGA.TO', 'Natural capital', 'Natural capital, nonrenewable assets: gas (constant 2018 US$)') into table...

Inserting record ('NW.NCA.MINR.TO', 'Natural capital', 'Natural capital, nonrenewable assets: minerals (constant 2018 US$)') into table...

Inserting record ('NW.NCA.SAOI.TO', 'Natural capital', 'Natural capital, nonrenewable assets: oil (constant 2018 US$)') into table...

Inserting record ('NW.NCA.PRAR.TO', 'Natural capital', 'Natural capital, protected areas (constant 2018 US$)') into table...

Inserting record ('NW.NCA.RNEW.TO', 'Natural capital', 'Natural capital, renewable (constant 2018 US$)') into table...

Inserting record ('NW.NFA.TO', 'Net foreign assets', 'Net foreign assets (constant 2018 US$)') into table...

Inserting record ('NW.NFA.PC', 'Net foreign assets', 'Net foreign assets per capita (constant 2018 US$)') into table...

Inserting record ('NW.PCA.TO', 'Produced capital', 'Produced capital (constant 2018 US$)') into table...

Inserting record ('NW.PCA.PC', 'Produced capital', 'Produced capital per capita (constant 2018 US$)') into table...

Inserting record ('NW.TOW.TO', 'Total wealth', 'Total wealth (constant 2018 US$)') into table...

Inserting record ('NW.TOW.PC', 'Total wealth', 'Total wealth per capita (constant 2018 US$)') into table...

Printing records from table...

('series_code', 'topic', 'indicator_name')
('NW.HCA.TO', 'Human capital', 'Human capital (constant 2018 US$)')
('NW.HCA.PC', 'Human capital', 'Human capital per capita (constant 2018 US$)')
('NW.HCA.FEMP.PC', 'Human capital', 'Human capital per capita, employed female (constant 2018 US$)')
('NW.HCA.MEMP.PC', 'Human capital', 'Human capital per capita, employed male (constant 2018 US$)')
('NW.HCA.FEMA.PC', 'Human capital', 'Human capital per capita, female (constant 2018 US$)')
('NW.HCA.MALE.PC', 'Human capital', 'Human capital per capita, male (constant 2018 US$)')
('NW.HCA.FSEM.PC', 'Human capital', 'Human capital per capita, self-employed female (constant 2018 US$)')
('NW.HCA.MSEM.PC', 'Human capital', 'Human capital per capita, self-employed male (constant 2018 US$)')
('NW.HCA.FEMP.TO', 'Human capital', 'Human capital, employed female (constant 2018 US$)')
('NW.HCA.MEMP.TO', 'Human capital', 'Human capital, employed male (constant 2018 US$)')
('NW.HCA.FEMA.TO', 'Human capital', 'Human capital, female (constant 2018 US$)')
('NW.HCA.MALE.TO', 'Human capital', 'Human capital, male (constant 2018 US$)')
('NW.HCA.FSEM.TO', 'Human capital', 'Human capital, self-employed female (constant 2018 US$)')
('NW.HCA.MSEM.TO', 'Human capital', 'Human capital, self-employed male (constant 2018 US$)')
('NW.NCA.TO', 'Natural capital', 'Natural capital (constant 2018 US$)')
('NW.NCA.PC', 'Natural capital', 'Natural capital per capita (constant 2018 US$)')
('NW.NCA.AGRI.PC', 'Natural capital', 'Natural capital per capita, agricultural land (constant 2018 US$)')
('NW.NCA.CROL.PC', 'Natural capital', 'Natural capital per capita, agricultural land: cropland (constant 2018 US$)')
('NW.NCA.PASL.PC', 'Natural capital', 'Natural capital per capita, agricultural land: pastureland (constant 2018 US$)')
('NW.NCA.FISH.PC', 'Natural capital', 'Natural capital per capita, fisheries (constant 2018 US$)')
('NW.NCA.FECO.PC', 'Natural capital', 'Natural capital per capita, forests: ecosystem services (constant 2018 US$)')
('NW.NCA.FTIM.PC', 'Natural capital', 'Natural capital per capita, forests: timber (constant 2018 US$)')
('NW.NCA.FOSL.PC', 'Natural capital', 'Natural capital per capita, fossil fuels (constant 2018 US$)')
('NW.NCA.MANG.PC', 'Natural capital', 'Natural capital per capita, mangroves (constant 2018 US$)')
('NW.NCA.SSOI.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets (constant 2018 US$)')
('NW.NCA.SACO.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: coal (constant 2018 US$)')
('NW.NCA.SAGA.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: gas (constant 2018 US$)')
('NW.NCA.MINR.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: minerals (constant 2018 US$)')
('NW.NCA.SAOI.PC', 'Natural capital', 'Natural capital per capita, nonrenewable assets: oil (constant 2018 US$)')
('NW.NCA.PRAR.PC', 'Natural capital', 'Natural capital per capita, protected areas (constant 2018 US$)')
('NW.NCA.RNEW.PC', 'Natural capital', 'Natural capital per capita, renewable (constant 2018 US$)')
('NW.NCA.AGRI.TO', 'Natural capital', 'Natural capital, agricultural land (constant 2018 US$)')
('NW.NCA.CROL.TO', 'Natural capital', 'Natural capital, agricultural land: cropland (constant 2018 US$)')
('NW.NCA.PASL.TO', 'Natural capital', 'Natural capital, agricultural land: pastureland (constant 2018 US$)')
('NW.NCA.FISH.TO', 'Natural capital', 'Natural capital, fisheries (constant 2018 US$)')
('NW.NCA.FECO.TO', 'Natural capital', 'Natural capital, forests: ecosystem services (constant 2018 US$)')
('NW.NCA.FTIM.TO', 'Natural capital', 'Natural capital, forests: timber (constant 2018 US$)')
('NW.NCA.FOSL.TO', 'Natural capital', 'Natural capital, fossil fuels (constant 2018 US$)')
('NW.NCA.MANG.TO', 'Natural capital', 'Natural capital, mangroves (constant 2018 US$)')
('NW.NCA.SSOI.TO', 'Natural capital', 'Natural capital, nonrenewable assets (constant 2018 US$)')
('NW.NCA.SACO.TO', 'Natural capital', 'Natural capital, nonrenewable assets: coal (constant 2018 US$)')
('NW.NCA.SAGA.TO', 'Natural capital', 'Natural capital, nonrenewable assets: gas (constant 2018 US$)')
('NW.NCA.MINR.TO', 'Natural capital', 'Natural capital, nonrenewable assets: minerals (constant 2018 US$)')
('NW.NCA.SAOI.TO', 'Natural capital', 'Natural capital, nonrenewable assets: oil (constant 2018 US$)')
('NW.NCA.PRAR.TO', 'Natural capital', 'Natural capital, protected areas (constant 2018 US$)')
('NW.NCA.RNEW.TO', 'Natural capital', 'Natural capital, renewable (constant 2018 US$)')
('NW.NFA.TO', 'Net foreign assets', 'Net foreign assets (constant 2018 US$)')
('NW.NFA.PC', 'Net foreign assets', 'Net foreign assets per capita (constant 2018 US$)')
('NW.PCA.TO', 'Produced capital', 'Produced capital (constant 2018 US$)')
('NW.PCA.PC', 'Produced capital', 'Produced capital per capita (constant 2018 US$)')
('NW.TOW.TO', 'Total wealth', 'Total wealth (constant 2018 US$)')
('NW.TOW.PC', 'Total wealth', 'Total wealth per capita (constant 2018 US$)')

### Create index constraint on 'series_code' column of table 'accounts_series'

In [32]:
db_cursor.execute("CREATE INDEX idx_series_code ON accounts_series ( series_code )")

### Create relationship between 'accounts_data' to 'accounts_series' by making column 'indicator_code' in 'accounts_data' a FOREIGN KEY

In [33]:
db_cursor.execute("ALTER TABLE accounts_data ADD FOREIGN KEY (indicator_code) REFERENCES accounts_series(series_code)")

### Create index constraint on 'country_code' column of table 'accounts_data'

In [34]:
db_cursor.execute("CREATE INDEX idx_country_code ON accounts_data ( country_code )")

### Create relationship between 'accounts_country' to 'accounts_data' by making column 'country_code' in 'accounts_country' a FOREIGN KEY

In [35]:
db_cursor.execute("ALTER TABLE accounts_country ADD FOREIGN KEY (country_code) REFERENCES accounts_data(country_code)")

### Close cursor

In [36]:
db_cursor.close()

True